export const USERS = "https://64673884ba7110b663b25c9c.mockapi.io/api/users";
export const RANDOM_MEAL_API =
  "https://www.themealdb.com/api/json/v1/1/random.php";
export const MEALS_LIST_API =
  "https://www.themealdb.com/api/json/v1/1/search.php?s=";
export const MEALS = "https://64673884ba7110b663b25c9c.mockapi.io/api/meals";
export const SHARED_MEALS =
  "https://64673884ba7110b663b25c9c.mockapi.io/api/sharedMeals";
